[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Cupertino-Dark
Comment=A MacOS Tahoe like Gtk+ theme based on Elegant Design
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Cupertino-Dark
MetacityTheme=Cupertino-Dark
IconTheme=Cupertino-dark
CursorTheme=mate
CursorSize=24
NotificationTheme=coco
ButtonLayout=close,minimize,maximize:menu

BackgroundImage=/usr/share/backgrounds/cupertino/cupertino-night.jpeg
